{{- if .Values.OpenServiceMesh.deployGrafana}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: osm-grafana
  name: osm-grafana

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: osm-grafana
  name: {{.Release.Name}}-grafana
rules: []

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Release.Name}}-grafana
  labels:
    app: osm-grafana
subjects:
  - kind: ServiceAccount
    name: osm-grafana
    namespace: {{.Release.Name}}
roleRef:
  kind: ClusterRole
  name: {{.Release.Name}}-grafana
  apiGroup: rbac.authorization.k8s.io
{{- end }}