{{- if .Values.OpenServiceMesh.deployGrafana}}
apiVersion: v1
kind: Service
metadata:
  name: osm-grafana
  namespace: {{ include "osm.namespace" . }}
  labels:
    {{- include "osm.labels" . | nindent 4 }}
    app: osm-grafana
spec:
  ports:
    - port: {{.Values.OpenServiceMesh.grafana.port}}
      name: grafana-dashboard
{{- if .Values.OpenServiceMesh.grafana.enableRemoteRendering}}
    - port: 8081
      name: grafana-renderer
{{- end }}
  selector:
    app: osm-grafana
{{- end }}
