apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    {{- include "osm.labels" . | nindent 4 }}
    app: osm-injector
  name: {{.Values.OpenServiceMesh.webhookConfigNamePrefix}}-{{.Values.OpenServiceMesh.meshName}}
webhooks:
- name: osm-inject.k8s.io
  clientConfig:
    service:
      name: osm-injector
      namespace: {{ include "osm.namespace" . }}
      path: /mutate-pod-creation
      port: 9090
  # failurePolicy should always be set to Fail to ensure no new resources get created without a sidecar
  #   (and bypass TrafficTarget policies) if the webhook server is down
  failurePolicy: Fail
  matchPolicy: Exact
  namespaceSelector:
    matchLabels:
      openservicemesh.io/monitored-by: {{.Values.OpenServiceMesh.meshName}}
    matchExpressions:
      # This label is explicitly set to ignore a namespace
      - key: "openservicemesh.io/ignore"
        operator: DoesNotExist

      # This label is set by Helm when it creates a namespace (https://github.com/helm/helm/blob/release-3.2/pkg/action/install.go#L292)
      # It ensures that pods in the control plane namespace are never injected with a sidecar
      - key: "name"
        operator: NotIn
        values:
        - {{ include "osm.namespace" . }}
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      operations:
        - CREATE
      resources:
        - pods
  # Injector's mutating webhook has a side effect of creating k8s secret for the Envoy bootstrap config.
  # For dry-run requests, this side effect is skipped.
  # Ref: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#side-effects
  sideEffects: NoneOnDryRun
  # Default timeout is 10s. Set this to 20s to account for slowness in scale environments
  timeoutSeconds: 20
  admissionReviewVersions: ["v1"]
