apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app: osm-controller
  name: {{.Values.OpenServiceMesh.webhookConfigNamePrefix}}-{{.Values.OpenServiceMesh.meshName}}
webhooks:
- name: osm-inject.k8s.io
  clientConfig:
    service:
      name: osm-controller
      namespace: {{.Release.Namespace}}
      path: /mutate-pod-creation
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  namespaceSelector:
    matchLabels:
      openservicemesh.io/monitored-by: {{.Values.OpenServiceMesh.meshName}}
    matchExpressions:
      # This label is explicitly set to ignore a namespace
      - key: "openservicemesh.io/ignore"
        operator: DoesNotExist

      # This label is set by Helm when it creates a namespace (https://github.com/helm/helm/blob/release-3.2/pkg/action/install.go#L292)
      # It ensures that pods in the control plane namespace are never injected with a sidecar
      - key: "name"
        operator: NotIn
        values:
        - {{.Release.Namespace}}
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      operations:
        - CREATE
      resources:
        - pods
