{{- if not .Values.OpenServiceMesh.enableReconciler }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    {{- include "osm.labels" . | nindent 4 }}
    app: osm-controller
  name: {{ include "osm.validatorWebhookConfigName" . }}
webhooks:
- name: osm-validator.k8s.io
  clientConfig:
    service:
      name: osm-validator
      namespace: {{ include "osm.namespace" . }}
      path: /validate
      port: 9093
  failurePolicy: Fail
  matchPolicy: Exact
  namespaceSelector:
    matchLabels:
      openservicemesh.io/monitored-by: {{.Values.OpenServiceMesh.meshName}}
    matchExpressions:
      # This label is explicitly set to ignore a namespace
      - key: "openservicemesh.io/ignore"
        operator: DoesNotExist
      # This label is set by Helm when it creates a namespace (https://github.com/helm/helm/blob/release-3.2/pkg/action/install.go#L292)
      # It ensures that pods in the control plane namespace are never injected with a sidecar
      - key: "name"
        operator: NotIn
        values:
        - {{ include "osm.namespace" . }}
  rules:
    - apiGroups:
        - policy.openservicemesh.io
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - ingressbackends
        - egresses
    {{- if .Values.smi.validateTrafficTarget }}
    - apiGroups:
        - access.smi-spec.io
      apiVersions:
        - v1alpha3
      operations:
        - CREATE
        - UPDATE
      resources:
        - traffictargets
    {{- end }}
  sideEffects: NoneOnDryRun
  admissionReviewVersions: ["v1"]
{{- end }}
