{{- if .Values.OpenServiceMesh.deployPrometheus }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osm-prometheus
  namespace: {{ include "osm.namespace" . }}
  labels:
    {{- include "osm.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: osm-prometheus
  template:
    metadata:
      labels:
        {{- include "osm.labels" . | nindent 8 }}
        app: osm-prometheus
    spec:
      {{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
      {{- include "restricted.securityContext" . | nindent 6 }}
      {{- end }}
      containers:
      - name: prometheus
        ports:
        - containerPort: {{.Values.OpenServiceMesh.prometheus.port}}
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus/
        - --storage.tsdb.retention.time={{.Values.OpenServiceMesh.prometheus.retention.time}}
        - --web.listen-address=:{{.Values.OpenServiceMesh.prometheus.port}}
        image: prom/prometheus:v2.18.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "{{.Values.OpenServiceMesh.prometheus.resources.limits.cpu}}"
            memory: "{{.Values.OpenServiceMesh.prometheus.resources.limits.memory}}"
          requests:
            cpu: "{{.Values.OpenServiceMesh.prometheus.resources.requests.cpu}}"
            memory: "{{.Values.OpenServiceMesh.prometheus.resources.requests.memory}}"
        volumeMounts:
        - mountPath: /etc/prometheus/
          name: prometheus-config-volume
        - mountPath: /prometheus/
          name: prometheus-storage-volume
      serviceAccountName: osm-prometheus
      volumes:
      - name: prometheus-config-volume
        configMap:
          defaultMode: 420
          name: osm-prometheus-server-conf
      - name: prometheus-storage-volume
        emptyDir: {}
{{- end }}
