{{- if .Values.OpenServiceMesh.deployPrometheus }}
apiVersion: v1
kind: Service
metadata:
  name: osm-prometheus
  annotations:
    prometheus.io/port: "{{.Values.OpenServiceMesh.prometheus.port}}"
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: {{.Values.OpenServiceMesh.prometheus.port}}
    protocol: TCP
    targetPort: {{.Values.OpenServiceMesh.prometheus.port}}
  selector:
    app: osm-prometheus
{{- end }}