apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-{{.Release.Name}}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{.Values.prometheus.labelSelector}}
  template:
    metadata:
      labels:
        app: {{.Values.prometheus.labelSelector}}
    spec:
      containers:
      - name: prometheus
        ports:
        - containerPort: {{.Values.prometheus.port}}
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus/
        - --storage.tsdb.retention.time={{.Values.prometheus.retention.time}}
        - --web.listen-address=:{{.Values.prometheus.port}}
        image: prom/prometheus:v2.18.1
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/prometheus/
          name: prometheus-config-volume
        - mountPath: /prometheus/
          name: prometheus-storage-volume
      serviceAccountName: prometheus-{{.Release.Name}}-serviceaccount
      volumes:
      - name: prometheus-config-volume
        configMap:
          defaultMode: 420
          name: prometheus-server-conf-{{.Release.Name}}
      - name: prometheus-storage-volume
        emptyDir: {}
