# Deploy bookstore-v1 Service
apiVersion: v1
kind: Service
metadata:
  name: bookstore-v1
  namespace: bookstore
  labels:
    app: bookstore
    version: v1
spec:
  ports:
  - port: 80
    name: bookstore-port
  selector:
    app: bookstore
    version: v1
---
# Deploy bookstore-v2 Service
apiVersion: v1
kind: Service
metadata:
  name: bookstore-v2
  namespace: bookstore
  labels:
    app: bookstore
    version: v2
spec:
  ports:
  - port: 80
    name: bookstore-port
  selector:
    app: bookstore
    version: v2
