# Deploy bookthief Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: bookthief
---
# Deploy bookthief ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookthief
  namespace: bookthief
---
# Deploy bookthief Service
apiVersion: v1
kind: Service
metadata:
  name: bookthief
  namespace: bookthief
  labels:
    app: bookthief
spec:
  ports:
  - port: 9999
    name: dummy-unused-port
  selector:
    app: bookthief
---
# Deploy bookthief Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookthief
  namespace: bookthief
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookthief
  template:
    metadata:
      labels:
        app: bookthief
        version: v1
    spec:
      serviceAccountName: bookthief
      containers:
        - name: bookthief
          image: openservicemesh/bookthief:v0.2.0
          imagePullPolicy: Always
          command: ["/bookthief"]
          env:
            - name: "BOOKSTORE_NAMESPACE"
              value: bookstore
            - name: "BOOKSTORE_SVC"
              value: bookstore
            - name: "BOOKTHIEF_EXPECTED_RESPONSE_CODE"
              value: "503"
