apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:  
  name: httproutegroups.specs.smi-spec.io
spec:
  group: specs.smi-spec.io
  version: v1alpha1
  scope: Namespaced 
  names:
    kind: HTTPRouteGroup
    shortNames: 
      - htr
    plural: httproutegroups
    singular: httproutegroup

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:  
  name: tcproutes.spec.smi-spec.io
spec:  
  group: spec.smi-spec.io
  version: v1alpha1
  scope: Namespaced 
  names:    
    kind: TCPRoute
    shortNames: 
      - tr
    plural: tcproutes
    singular: tcproute
