# Deploy bookstore Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: bookstore
---
# Deploy bookstore-v1 Service
apiVersion: v1
kind: Service
metadata:
  name: bookstore-v1
  namespace: bookstore
  labels:
    app: bookstore
    version: v1
spec:
  ports:
  - port: 14001
    name: bookstore-port
  selector:
    app: bookstore-v1
---
# Deploy bookstore-v1 Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookstore-v1
  namespace: bookstore
---
# Deploy bookstore-v1 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-v1
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-v1
  template:
    metadata:
      labels:
        app: bookstore-v1
    spec:
      serviceAccountName: bookstore-v1
      containers:
        - name: bookstore
          image: openservicemesh/bookstore:v0.8.0-rc.1
          imagePullPolicy: Always
          ports:
            - containerPort: 14001
              name: web
          command: ["/bookstore"]
          args: ["--path", "./", "--port", "14001"]
          env:
            - name: BOOKWAREHOUSE_NAMESPACE
              value: bookwarehouse
            - name: IDENTITY
              value: bookstore-v1
